process.env.DB_USER = 'user'
process.env.DB_PASSWORD = 'password'
process.env.DB_DATABASE = 'dbName'
process.env.DB_HOST = '111.222.111'
process.env.DB_PORT = '3000'
process.env.PORT = '1234'

process.env.OPEN_WEATHER_API_KEY = 'open_weather_api_key'

process.env.FIREBASE_PROJECT_ID = 'project_id'
process.env.FIREBASE_STORAGE_BUCKET = 'storage_bucket'
process.env.FIREBASE_ADMIN_PRIVATE_KEY_ID = 'admin_private_key_id'
process.env.FIREBASE_ADMIN_PRIVATE_KEY = 'sample\\ntest'
process.env.FIREBASE_ADMIN_CLIENT_EMAIL = 'admin_client_email'
process.env.FIREBASE_ADMIN_CLIENT_ID = 'admin_client_id'
process.env.FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL = 'admin_auth_cert_url'
process.env.FIREBASE_ADMIN_CLIENT_X509_CERT_URL = 'admin_client_cert_url'
