name: General Testing for CI

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm ci --prefer-offline --no-audit --ignore-scripts
    - run: npm run lint
    - run: npm run typecheck
    - run: npm run test:ci
    - name: Archive code coverage results
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/

  coverage:
    if: (success() || failure()) && github.event_name == 'pull_request'
    needs: codecheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: code-coverage-report
        path: coverage/
    - uses: ArtiomTr/jest-coverage-report-action@v2
      id: coverage
      with:
        skip-step: all
        coverage-file: coverage/coverage-final.json
        base-coverage-file: coverage/coverage-final.json
        output: report-markdown
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: ${{ steps.coverage.outputs.report }}
